export const Questions = [
    {
        prompt: "What country was 2018 FIFA World Cup hosted? ",
        optionA: "Brazil",
        optionB: "Russia",
        optionC: "France",
        optionD: "Germany",
        answer: "B",
    },
    {
        prompt: "What country was 2014 FIFA World Cup hosted? ",
        optionA: "Brazil",
        optionB: "Russia",
        optionC: "France",
        optionD: "Germany",
        answer: "A",
    },
    {
        prompt: "What country won 2018 FIFA World Cup? ",
        optionA: "Brazil",
        optionB: "Russia",
        optionC: "France",
        optionD: "Germany",
        answer: "C",
    },
    {
        prompt: "What country won 2014 FIFA World Cup hosted? ",
        optionA: "Brazil",
        optionB: "Russia",
        optionC: "France",
        optionD: "Germany",
        answer: "D",
    },
    {
        prompt: "What country was 2006 FIFA World Cup hosted? ",
        optionA: "Brazil",
        optionB: "Russia",
        optionC: "France",
        optionD: "Germany",
        answer: "D",
    },
];